[build]
  command = "npm run build"
  publish = "dist"

# Handle form submissions
[build.processing.html]
  pretty_urls = true

# Redirect and rewrite rules
[[redirects]]
  from = "/form-success"
  to = "/form-success.html"
  status = 200
  force = true

[[redirects]]
  from = "/success"
  to = "/success/"
  status = 301
  force = true

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Enable build hooks
[build.environment]
  NETLIFY_USE_YARN = "true"